### ISSUE TITLE
Should connect_startup take FnOnce instead of Fn?

### ISSUE THREAD

**Issue by mattiasflodin** [gtk-rs/gio#169]
Say you load some information that will be used in the rendering of your window. You want to pass it into your application init so it can eventually be used in the drawing handler to govern what gets drawn:

```
fn main() {
    let info = load_info();
    /// ...
    application.connect_startup(move |app| {
        build_ui(app, info);
    };
}

fn build_ui(app: &Application, info: DrawingInfo) {
    // ...
    drawing_area.connect_draw(move |w: &DrawingArea, ctx: &cairo:Context| {
        do_drawing(&info);
    });
}
```

Now you have a problem because you can't move `info` out of the `connect_startup()` closure, because Rust thinks the startup closure may be called multiple times. You could try passing a reference to `info` to `build_ui` instead, but then you get lifetime issues because `connect_draw` wants reference members in the closure to have static lifetime.

I don't see a way around this without either needlessly putting `info` in an `Rc`, or cloning it (but then it will forever live in the `connect_startup` closure even though it's only used once).

Put in another perspective, if the `connect_startup()` closure is large then it will use a lot of memory for the entire running time of the program, even though it is only called once (right?). So, I'm thinking, shouldn't `connect_startup` take an `FnOnce` instead of `Fn`? That would allow objects to be moved out of the `connect_startup` closure and the code above would work.

The same goes for other event handlers that are only called once.

**Comment by sdroege** [comment]
The problem here is that there's no indication from the API introspection data if the signal is only called once (`FnOnce`) or multiple times (`FnMut`) or even multiple times at the same time from different threads or reentrant (`Fn`).

We could add some configuration for overriding the default safe choice of `Fn`, that would certainly make sense.

----

Independent of that, you probably won't get around putting some of your data into an `Rc<RefCell<_>>` or similar sooner or later. Due to the callback-based nature of GTK this can't really be prevented.

**Comment by sdroege** [comment]
Let's close this for now until there's a way to solve this in a generic way
