### ISSUE TITLE
Bind GIOChannel 

### ISSUE THREAD

**Issue by gdesmott** [gtk-rs/gio#311]
Would be nice to have proper `GIOChannel` bindings at some point.

**Comment by ebassi** [comment]
Just a note:

 - `GIOChannel` is a very old API that has some pitfalls
 - introspectability is somewhat dubious because of the age
 - some symbols appear depending on the platform that generated the introspection data
 - the API interfaces itself directly with low level data types (file descriptors of various nature) which may or may not be safe in Rust
 - use outside of Unix-like systems is still iffy

GIOChannel may still be good for small, throwaway code that only ever runs on Linux, and only need a simple main loop.

It is highly recommended newly written programs/modules use GIO and the input/output streams instead.

**Comment by GuillaumeGomez** [comment]
Thanks for the note!

**Comment by sdroege** [comment]
This is in GLib, not GIO. See https://github.com/gtk-rs/glib/issues/186
